application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      extension-config:
        license: Apache-2.0
        actions:
          extension-config:
            function: actions/extension-config/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          extension-config-event:
            function: actions/extension-config-event/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
